### ISSUE TITLE
Missing /etc/vso/config.json during building

### ISSUE THREAD

**Issue by D3vil0p3r** [Vanilla-OS/vanilla-control-center#163]
After a successful building of Vanilla Control Center, if `vanilla-control-center` is run, the following issue is produced:
```
Traceback (most recent call last):
  File "/usr/local/share/vanilla-control-center/vanilla_control_center/main.py", line 89, in do_activate
    win = VanillaWindow(application=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/vanilla-control-center/vanilla_control_center/window.py", line 64, in __init__
    self.__build_ui()
  File "/usr/local/share/vanilla-control-center/vanilla_control_center/window.py", line 67, in __build_ui
    self.__setup_vso()
  File "/usr/local/share/vanilla-control-center/vanilla_control_center/window.py", line 75, in __setup_vso
    if scheduling := self.vso.scheduling:
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/vanilla-control-center/vanilla_control_center/backends/vso.py", line 65, in scheduling
    return self.get_config()["updates"]["schedule"]
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/share/vanilla-control-center/vanilla_control_center/backends/vso.py", line 61, in get_config
    raise FileNotFoundError(_("VSO Config file not found at {}").format(self.__conf_path))
FileNotFoundError: VSO Config file not found at /etc/vso/config.json
```
Is it possible to add the creation of `/etc/vso/config.json` with the following code, inside meson build?
```json
{
  "updates": {
    "schedule": "weekly",
    "smart": true
  }
}
```

**Comment by mirkobrombin** [comment]
why are you building vso and the control center? If you are trying to pack it for another distro, take note that both projects are not distro agnostic

**Comment by D3vil0p3r** [comment]
Yes I'm using Arch, but now I see that this config file is generated by Vanilla System Operator project piece. So I can package VSO and use it as dependency of Vanilla Control Center.

My fault, closing the issue.
